### ISSUE TITLE
Missing phantom.mhd in /dosimetry/Radiotherapy/example10/data

### ISSUE THREAD

**Issue by Athropos** [OpenGATE/GateContrib#13]
Hello,

I'm working on my Bachelor's final project and I needed exemple of dose evaluation with TLE and seTLE. I noticed that in the example of my interest the file .mhd of the phantom thorax is missing. Can anyone fix this as soon as possible?

Thank you in advance,

Nicola Rizzi

**Comment by dsarrut** [comment]
Done with commit e549779
