### ISSUE TITLE
Opening mhd/raw output files

### ISSUE THREAD

**Issue by Milan991** [OpenGATE/GateContrib#30]
What software should be used for opening .mhd/.raw output files?
I've tried multiple softwares but none of them showed desired results. I've tested it with output files from dosimetry examples.

I would like to see 3D images like in the picture below:

![mp1617-fig-0003-m](https://user-images.githubusercontent.com/13959599/62430858-6bfca000-b722-11e9-8573-8bf2145b5f5f.jpg)

**Comment by tbaudier** [comment]
Hi @Milan991 

For this kind of question you can use the mailing list, you will have a quicker answer next time:
http://www.opengatecollaboration.org/mailinglist

By the way, to open .mhd/.raw images you can use multiple software:
https://www.slicer.org/
https://www.creatis.insa-lyon.fr/rio/vv
