### ISSUE TITLE
use ct dicom in gate for dosimetry and rt simulation

### ISSUE THREAD

**Issue by amirbahador28568** [OpenGATE/GateContrib#34]
Hi everyone
I want use 90 slice of ct dicom(head) in gate as a phantom for dosimetry like example 2 but i dont now how use them
is there any way to convert these 90 dicom into 1 dicom for attaching actor?cuz I want gate simulate head of patient
or is thee any way or command to use all dicom and attach dose actor to them for dosimetry?
Thanks for Your help

**Comment by dsarrut** [comment]
Hello, see https://github.com/OpenGATE/GateContrib/tree/master/imaging/DICOM/mhd-dcm-comparison. If I remember well, in the macro, give only one dcm filename of the whole series and Gate will read all the files. 

HTH
David

**Comment by amirbahador28568** [comment]
thanks for guide
you mean if I give my dicom it will create a single dicom or mhd file?

> Hello, see https://github.com/OpenGATE/GateContrib/tree/master/imaging/DICOM/mhd-dcm-comparison. If I remember well, in the macro, give only one dcm filename of the whole series and Gate will read all the files.
> 
> HTH
> David

**Comment by dsarrut** [comment]
not really: in your macro just give the name of your first Dicom file. GATE should read all other files in the same folder, based on the Dicom UID.

Another solution is to convert your Dicom into a single MHD file.

**Comment by amirbahador28568** [comment]
how 

> not really: in your macro just give the name of your first Dicom file. GATE should read all other files in the same folder, based on the Dicom UID.
> 
> Another solution is to convert your Dicom into a single MHD file.

oh i after this method.
how can i convert dicom series in single mhd/raw file?i try several time but couldnt do this.if you know anyway pls guide me
