### ISSUE TITLE
imageCT input data

### ISSUE THREAD

**Issue by ajowzaee** [OpenGATE/GateContrib#57]
Hi, I am doing a dual layer CT simulation using Gate. I want to extract imageCT for each detector layer, however there is no command as /gate/output/imageCT/setInputDataName or like this to define the input data for image CT. I did it in digitizer for hits and singles in a Root file, but I need imageCT output of both layers. Please advise!

**Comment by dsarrut** [comment]
Hello, sorry, please ask on the mailing list
