### ISSUE TITLE
why is LUTDavisModel changed?

### ISSUE THREAD

**Issue by tontyoutoure** [OpenGATE/GateContrib#70]
hi, I'm trying to do some optical simulation with Gate and want to find some examples. I tries to run LUTDavisModel example and it fails and says 
```
The optical surface 'RoughTeflon_LUT' could not be created!
The optical surface 'RoughTeflon_LUT' could not be created!
The optical surface 'Detector_LUT' could not be created!
The optical surface 'Detector_LUT' could not be created!
```
after a while I noticed that @kochebina had changed `Surface.xml` and it seemed to me caused that problem. I notice that there are two ways of optical surface definition in Gate: the LUTDavis one and the UNIFIED one. It seems to me the change looks like an UNIFIED one, while the example is about the LUTDavis Model. Could you explain why that change is made? I uses Gate 9.3 from vGate.

**Comment by kochebina** [comment]
Dear @tontyoutoure, 

In my case (Gate9.3 from git/develop) the example works perfectly and I don't have this error message. 
However, it seems you are right: while moving some files in this rep I coped the wrong Surface.xml.
Thank you for noticing! 

Cheers,
Olga

**Comment by tontyoutoure** [comment]
Glad to contribute!
